[package]
name = "uwc"
version = "0.1.0"
authors = ["Skyler Hawthorne <skylerhawthorne@gmail.com>"]
description = "Counts things in unicode text files"
respository = "https://github.com/dead10ck/uwc"
readme = "README.md"

keywords = [ "wc", "unicode", "word", "count" ]
categories = [ "command-line-utilities", "text-processing" ]
license = "MPL-2.0"

[badges]
travis-ci = { repository = "dead10ck/uwc", branch = "master" }

[dependencies]
unicode-segmentation = "^1.2.0"
log = "^0.3.8"
env_logger = "^0.4.3"
lazy_static = "^0.2.10"
structopt = "^0.1"
structopt-derive = "^0.1"
failure = "^0.1.1"
tabwriter = "^1.0.3"
#rayon = "^0.9"

#[profile.release]
#debug = true
