[package]
name = "uwc"
version = "0.1.0"
authors = ["Skyler Hawthorne <skylerhawthorne@gmail.com>"]

[dependencies]
unicode-segmentation = "^1.2.0"
log = "^0.3.8"
env_logger = "^0.4.3"
lazy_static = "^0.2.10"

[dependencies.clap]
version = "^2.27.1"
features = [ "color" ]
